name: Go AWS nitro enclave attestation document authentication module

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      
      - name: Check formatting
        uses: Jerome1337/gofmt-action@v1.0.4
        with:
          gofmt-path: '.'
          gofmt-flags: '-l -d'

      - name: Build
        run: go build 

      - name: Test
        run: go test
